name: Master CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build and Push Dockerfile
        uses: matootie/github-docker@v2.0.0
        with:
          imageName: ${{ github.event.repository.name }}-master
          accessToken: ${{ secrets.GITHUB_TOKEN }}
